#ifdef MKISOSU_H_INCLUDED
	#define MKISOSU_H_INCLUDED
	#define EXTERN 
#else
	#define EXTERN extern
#endif

EXTERN double Sotowaku[MAX_SHUBETU][SAISHUNENDO - SOTOWAKU_SHONENDO + 1][MAX_WAKU_NENREI - MIN_WAKU_NENREI + 1];
EXTERN double Sotowaku_2gou[SEIBETU][SAISHUNENDO - SOTOWAKU_SHONENDO + 1][MAX_WAKU_NENREI - MIN_WAKU_NENREI + 1];
EXTERN double Hiho_Kei[MAX_SHUBETU][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 2];
EXTERN double Hiho_Noufu[MAX_SHUBETU][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 2];
EXTERN double Hiho_Menjo[MAX_SHUBETU][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 2]
		[MENJO_JOKYO];
EXTERN double Fuka_Hiho[MAX_SHUBETU][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 2];
EXTERN double Hiho_Kei_P[MAX_SHUBETU][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 2];
EXTERN double Hiho_Noufu_P[MAX_SHUBETU][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 2];
EXTERN double Hiho_Menjo_P[MAX_SHUBETU][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 2]
		[MENJO_JOKYO];
EXTERN double Fuka_Hiho_P[MAX_SHUBETU][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 2];
EXTERN double Hiho_Kei_Nendokan[MAX_SHUBETU][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 2];
EXTERN double Hiho_Noufu_Nendokan[MAX_SHUBETU][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 2];
EXTERN double Hiho_Menjo_Nendokan[MAX_SHUBETU][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 2]
		[MENJO_JOKYO];
EXTERN double Fuka_Hiho_Nendokan[MAX_SHUBETU][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 2];
EXTERN double Hiho_Sankyu[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Hiho_Sankyu_Sum[SAISHUNENDO - SHONENDO + 1];
EXTERN double Hiho_Ikukyu[MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Hiho_Ikukyu_Sum[SAISHUNENDO - SHONENDO + 1];

EXTERN struct hihokensha
{
	double ninzu;
	double kikan;
	double noufu;
	double menjo[MENJO_DANKAI][KOKKO_HIKIAGE];
	double gakusei;
	double wakamono;
	double fuka;
}
Hihokensha[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1][MAX_HIHO_KIKAN + 1] ,
Taikisha[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1][MAX_HIHO_KIKAN + 1] ,
Hihokensha_Zero ,
Taikisha_Zero ,
Hihokensha2[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1][MAX_HIHO_KIKAN + 1] ,
Hihokensha_Shibou2[MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1][MAX_HIHO_KIKAN + 1];

EXTERN struct rorei
{
	double ninzu;
	double noufu;
	double menjo[MENJO_DANKAI][KOKKO_HIKIAGE];
	double rofuku_shitasasae;
	double fuka;
}
Rorei_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_ROREI_JUKYU - MIN_ROREI_JUKYU + 1][KURI_AGE_SAGE_SHIKYU_KUBUN] ,
Rorei_Ichibu_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_ROREI_JUKYU - MIN_ROREI_JUKYU + 1][KURI_AGE_SAGE_SHIKYU_KUBUN] ,
Rorei[MAX_SHUBETU + 3][SAISHUNENDO - SHONENDO + 1][MAX_ROREI_JUKYU - NENREI_SUM + 1][KURI_AGE_SAGE_SHIKYU_KUBUN + 1] ,
Shikyuritu_Rorei[SAISHUNENDO - SHONENDO + 1][MAX_ROREI_JUKYU - MIN_ROREI_JUKYU + 1] ,
Kakudai_Ichibu[SAISHUNENDO - MIN_ROREI_JUKYU - ( SHONENDO - MAX_ROREI_JUKYU ) + 1][KURI_AGE_SAGE_SHIKYU_KUBUN],
Rorei_Zero,
Rorei_Shinki2[KURI_AGE_SAGE_SHIKYU_KUBUN];

EXTERN struct rorei_kyu
{
	double ninzu;
	double noufu;
	double menjo;
	double kasa_noufu;
	double kasa_menjo;
	double rofuku_shitasasae;
	double fuka;
}
Rorei_Kyu_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_ROREI_JUKYU - MIN_ROREI_JUKYU + 1][KURI_AGE_SAGE_SHIKYU_KUBUN] ,
Rorei_Kyu[MAX_SHUBETU + 3][SAISHUNENDO - SHONENDO + 1][MAX_ROREI_JUKYU - NENREI_SUM + 1][KURI_AGE_SAGE_SHIKYU_KUBUN + 1] ,
Shikyuritu_Rorei_Kyu[SAISHUNENDO - SHONENDO + 1][MAX_ROREI_JUKYU - MIN_ROREI_JUKYU + 1] ,
Turo_Kyu_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_ROREI_JUKYU - MIN_ROREI_JUKYU + 1][KURI_AGE_SAGE_SHIKYU_KUBUN] ,
Turo_Kyu[MAX_SHUBETU + 3][SAISHUNENDO - SHONENDO + 1][MAX_ROREI_JUKYU - NENREI_SUM + 1][KURI_AGE_SAGE_SHIKYU_KUBUN + 1] ,
Shikyuritu_Turo_Kyu[SAISHUNENDO - SHONENDO + 1][MAX_ROREI_JUKYU - MIN_ROREI_JUKYU + 1] ,
Rorei_Kyu_Zero;

EXTERN struct gonen
{
	double ninzu;
	double noufu;
}
Gonen_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_ROREI_JUKYU - MIN_ROREI_JUKYU + 1][KURI_AGE_SAGE_SHIKYU_KUBUN] ,
Gonen[MAX_SHUBETU + 3][SAISHUNENDO - SHONENDO + 1][MAX_ROREI_JUKYU - NENREI_SUM + 1][KURI_AGE_SAGE_SHIKYU_KUBUN + 1],
Gonen_Zero;

EXTERN struct shogai
{
	double ninzu;
	double kihon;
	double kakyu;
	double menjo_kihon;
	double menjo_kakyu;
}
Shogai_Ippan_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1][SHOGAI_TOKYU] ,
Shogai_Ippan[MAX_SHUBETU + 3][SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - NENREI_SUM + 1] ,
Shogai_20mae_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1][SHOGAI_TOKYU] ,
Shogai_20mae[MAX_SHUBETU + 3][SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - NENREI_SUM + 1] ,
Shogai_Kyu_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1][SHOGAI_TOKYU] ,
Shogai_Kyu[MAX_SHUBETU + 3][SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - NENREI_SUM + 1] ,
Shogai_Zero;

EXTERN struct izoku
{
	double ninzu;
	double kihon;
	double kakyu;
}
Izoku_Tuma_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_IZOKU_TUMA_JUKYU - MIN_IZOKU_TUMA_JUKYU + 1] ,
Izoku_Tuma[MAX_SHUBETU + 3][SAISHUNENDO - SHONENDO + 1][MAX_IZOKU_TUMA_JUKYU - NENREI_SUM + 1] ,
Izoku_Otto_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_IZOKU_OTTO_JUKYU - MIN_IZOKU_OTTO_JUKYU + 1] ,
Izoku_Otto[MAX_SHUBETU + 3][SAISHUNENDO - SHONENDO + 1][MAX_IZOKU_OTTO_JUKYU - NENREI_SUM + 1] ,
Izoku_Ko_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_IZOKU_KO_JUKYU - MIN_IZOKU_KO_JUKYU + 1] ,
Izoku_Ko[MAX_SHUBETU + 3][SAISHUNENDO - SHONENDO + 1] ,
Izoku_Zero;

EXTERN struct kafu
{
	double ninzu;
	double noufu;
	double menjo[MENJO_DANKAI][KOKKO_HIKIAGE];
}
Kafu_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_KAFU_JUKYU - MIN_KAFU_JUKYU + 1] ,
Kafu[MAX_SHUBETU + 3][SAISHUNENDO - SHONENDO + 1] ,
Kafu_Kyu_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_KAFU_JUKYU - MIN_KAFU_JUKYU + 1] ,
Kafu_Kyu[MAX_SHUBETU + 3][SAISHUNENDO - SHONENDO + 1] ,
Kafu_Zero;

EXTERN struct ichijikin
{
	double ninzu;
	double kyufu;
	double kyufu_fuka;
}
Ichijikin_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1] , 
Ichijikin[MAX_SHUBETU + 3][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - NENREI_SUM + 1] ,
Ichijikin_Zero;
