#ifdef MKISORITU_H_INCLUDED
	#define MKISORITU_H_INCLUDED
	#define EXTERN 
#else
	#define EXTERN extern
#endif

EXTERN double Dattairyoku_Gokei[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Dattairyoku_Shibou[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Saikanyuritu[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double q[SHIKKENRITU_MAX - SHIKKENRITU_MIN + 1][MAX_ROREI_JUKYU - 1 - 0 + 1][2];
EXTERN double Noufuritu[MAX_SHUBETU][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1][MENJO_JOKYO];
EXTERN double Noufuritu_Fuka[MAX_SHUBETU][SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Hassei_Wariai_Rorei[SAISHUNENDO - SHONENDO + 1][KURI_AGE_SAGE_SHIKYU_KUBUN];
EXTERN double Shikkenritu_Rorei[SAISHUNENDO - SHONENDO + 1][MAX_ROREI_JUKYU - MIN_HIHO_NENREI + 1];
EXTERN double Waribikiritu[2][2][70 - 66 + 1][SUIKEISHONENDO + 10 - SUIKEISHONENDO + 1 + 1];
EXTERN double Kyufu_ritu[KURI_AGE_SAGE_SHIKYU_KUBUN][( SAISHUNENDO - MIN_ROREI_JUKYU ) - ( SHONENDO - 70 ) + 1][2];
EXTERN double Kyufu_ritu1[KURI_AGE_SAGE_SHIKYU_KUBUN][( SAISHUNENDO - MIN_ROREI_JUKYU ) - ( SHONENDO - 70 ) + 1][2];
EXTERN double Kyufu_ritu2[KURI_AGE_SAGE_SHIKYU_KUBUN][( SAISHUNENDO - MIN_ROREI_JUKYU ) - ( SHONENDO - 70 ) + 1][2];
EXTERN double Hasseiryoku_Shogai[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Hassei_Wariai_20mae[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Shikkenritu_Ippan[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1];
EXTERN double Shikkenritu_20mae[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1];
EXTERN double Tokyu_Wariai_20mae[SAISHUNENDO - SHONENDO + 1][SHOGAI_TOKYU];
EXTERN double Tokyu_Wariai_Ippan[SAISHUNENDO - SHONENDO + 1][SHOGAI_TOKYU];
EXTERN double Kakyu_Wariai_Ippan_12shi[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1];
EXTERN double Kakyu_Wariai_Ippan_3shiiko[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1];
EXTERN double Kakyu_Wariai_20mae_12shi[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1];
EXTERN double Kakyu_Wariai_20mae_3shiiko[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1];
EXTERN double Hassei_Wariai_Tuma[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Hassei_Wariai_Otto[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Hassei_Wariai_Ko[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Hassei_Wariai_Kafu[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Hassei_Wariai_Shibou[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Shikkenritu_Tuma[SAISHUNENDO - SHONENDO + 1][MAX_IZOKU_TUMA_JUKYU - MIN_IZOKU_TUMA_JUKYU + 1];
EXTERN double Shikkenritu_Otto[SAISHUNENDO - SHONENDO + 1][MAX_IZOKU_OTTO_JUKYU - MIN_IZOKU_OTTO_JUKYU + 1];
EXTERN double Shikkenritu_Ko[SAISHUNENDO - SHONENDO + 1][MAX_IZOKU_KO_JUKYU - MIN_IZOKU_KO_JUKYU + 1];
EXTERN double Shikkenritu_Kafu[SAISHUNENDO - SHONENDO + 1][MAX_KAFU_JUKYU - MIN_KAFU_JUKYU + 1];
EXTERN double Sokan_Tuma[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Sokan_Otto[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Sokan_Ko[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Sokan_Kafu[SAISHUNENDO - SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1];
EXTERN double Kakyu_Wariai_Tuma_12shi[SAISHUNENDO - SHONENDO + 1][MAX_IZOKU_TUMA_JUKYU - MIN_IZOKU_TUMA_JUKYU + 1];
EXTERN double Kakyu_Wariai_Tuma_3shiiko[SAISHUNENDO - SHONENDO + 1][MAX_IZOKU_TUMA_JUKYU - MIN_IZOKU_TUMA_JUKYU + 1];
EXTERN double Kakyu_Wariai_Otto_12shi[SAISHUNENDO - SHONENDO + 1][MAX_IZOKU_OTTO_JUKYU - MIN_IZOKU_OTTO_JUKYU + 1];
EXTERN double Kakyu_Wariai_Otto_3shiiko[SAISHUNENDO - SHONENDO + 1][MAX_IZOKU_OTTO_JUKYU - MIN_IZOKU_OTTO_JUKYU + 1];
EXTERN double Kakyu_Wariai_Ko_12shi[SAISHUNENDO - SHONENDO + 1][MAX_IZOKU_KO_JUKYU - MIN_IZOKU_KO_JUKYU + 1];
EXTERN double Kakyu_Wariai_Ko_3shiiko[SAISHUNENDO - SHONENDO + 1][MAX_IZOKU_KO_JUKYU - MIN_IZOKU_KO_JUKYU + 1];
EXTERN double Shikyuritu_Gonen[SAISHUNENDO - SHONENDO + 1][MAX_ROREI_JUKYU - MIN_ROREI_JUKYU + 1];
EXTERN double Shikyuritu_Shogai_Ippan[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1][SHOGAI_TOKYU];
EXTERN double Shikyuritu_Shogai_Ippan_keinen[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1][SHOGAI_TOKYU];
EXTERN double Shikyuritu_Shogai_20mae[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1][SHOGAI_TOKYU];
EXTERN double Shikyuritu_Shogai_20mae_keinen[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1][SHOGAI_TOKYU];
EXTERN double Shikyuritu_Shogai_Kyu[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1][SHOGAI_TOKYU];
EXTERN double Shikyuritu_Shogai_Kyu_keinen[SAISHUNENDO - SHONENDO + 1][MAX_SHOGAI_JUKYU - MIN_SHOGAI_JUKYU + 1][SHOGAI_TOKYU];
EXTERN double Shikyuritu_Tuma[SAISHUNENDO - SHONENDO + 1];
EXTERN double Shikyuritu_Otto[SAISHUNENDO - SHONENDO + 1];
EXTERN double Shikyuritu_Ko[SAISHUNENDO - SHONENDO + 1];
EXTERN double Shikyuritu_Kafu[SAISHUNENDO - SHONENDO + 1][MAX_KAFU_JUKYU - 60 + 1];
EXTERN double Izoku_Keinen[SAISHUNENDO - I_KEINEN_SHONENDO + 1][MAX_HIHO_NENREI - MIN_HIHO_NENREI + 1][2];
