#ifdef MCNTL_H_INCLUDED
	#define MCNTL_H_INCLUDED
	#define EXTERN 
#else
	#define EXTERN extern
#endif


EXTERN int kako;

EXTERN char HIYOUSYADATA[7];
EXTERN char KOKUNENDATA[7];
EXTERN char ECON[5];
EXTERN char SOTOWAKU[5];
EXTERN char SOTOWAKU_CUT[5];
EXTERN char YOBI[4];
EXTERN char Version[24];
EXTERN char Version_cut[10];
EXTERN char Version_tumatumi[100];
EXTERN char Version_Jurai[20];
EXTERN char HIYOUSYADATA_Jurai_KAKO[7];
EXTERN char KOKUNENDATA_Jurai_KAKO[7];
EXTERN int D_MACRO;
EXTERN int D_M_NENDO;
EXTERN int CARRY;
EXTERN int Kurikoshim;
EXTERN int CUT_KOTEI;
EXTERN int CUT_ONE_SHUTU;
EXTERN int C_NENDO;
EXTERN int S_C_NENDO;
EXTERN int T_NENDO;
EXTERN int T_DOAI;
EXTERN int KAISHI1;
EXTERN int KAISHI2;
EXTERN int MARUME_NENDO;
EXTERN int tuki[SAISHUNENDO - SHONENDO + 1];
EXTERN int FUKUSHI_NENDO;
EXTERN double hosei_shin[KYUFU_KUBUN][SAISHUNENDO - SHONENDO + 1];
EXTERN double hosei_kyu[6][SAISHUNENDO - SHONENDO + 1];
EXTERN double MODEL_PENSION;
EXTERN double MODEL_WAGE;
