#ifdef MECON_H_INCLUDED
	#define MECON_H_INCLUDED
	#define EXTERN 
#else
	#define EXTERN extern
#endif

EXTERN double cpi_up[SAISHUNENDO - ECON_SHONENDO + 1];
EXTERN double base_up[SAISHUNENDO - ECON_SHONENDO + 1];
EXTERN double base_up_k[SAISHUNENDO - ECON_SHONENDO + 1];
EXTERN double interest_rate[SAISHUNENDO - ECON_SHONENDO + 1];
EXTERN double kakaku[SAISHUNENDO - ECON_SHONENDO + 1];
EXTERN double pre_cut[SAISHUNENDO - ECON_SHONENDO + 1][MAX_JUKYU - UNDER_67 + 1];
EXTERN double T[SAISHUNENDO - ECON_SHONENDO + 1][MAX_JUKYU - UNDER_67 + 1];
EXTERN double cut_ruiseki[SAISHUNENDO - ECON_SHONENDO + 1][SAISHUNENDO - ECON_SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1];
EXTERN double ruiseki_interest_rate[SAISHUNENDO - ECON_SHONENDO + 1];
EXTERN double g_ruiseki_interest_rate[SAISHUNENDO - ECON_SHONENDO + 1];
EXTERN double kaiteiritu[SAISHUNENDO - ECON_SHONENDO + 1][MAX_JUKYU - UNDER_67 + 1];
EXTERN double kaiteiritu_cut[SAISHUNENDO - ECON_SHONENDO + 1][MAX_JUKYU - UNDER_67 + 1];
