#ifdef MKISOSU_H_INCLUDED
	#define MKISOSU_H_INCLUDED
	#define EXTERN 
#else
	#define EXTERN extern
#endif

EXTERN double Rorei_New[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[SEIBETU][NOUFU_JOTAI_SHIN];
EXTERN double Shogai_New[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[SEIBETU][KYUFU_HOUHOU][SHIKYU_KEITAI];
EXTERN double Izoku_New[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[SEIBETU][SHIKYU_KEITAI];
EXTERN double Rorei_Old[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[SEIBETU][NOUFU_JOTAI_KYU];
EXTERN double Shogai_Old[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[SEIBETU][SHIKYU_KEITAI][NOUFU_JOTAI_KYU - 6];
EXTERN double Izoku_Old[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[SEIBETU][SHIKYU_KEITAI][NOUFU_JOTAI_KYU - 6];
EXTERN double FurikaeKasan[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[SEIBETU][KYUFU_KUBUN - 1];
EXTERN double Kyufu[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[SHINKYU][KYUFU_KUBUN][KYUFU_TAISHOU][SHIKYU_KEITAI];
EXTERN double Kyufu_Nendomatu[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[SHINKYU][KYUFU_KUBUN][KYUFU_TAISHOU][SHIKYU_KEITAI];
EXTERN double Kyufu_Nendomatu_P[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[SHINKYU][KYUFU_KUBUN][KYUFU_TAISHOU][SHIKYU_KEITAI];
EXTERN double Kokko[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[SHINKYU][KYUFU_KUBUN][SHIKYU_KEITAI];
EXTERN double Kokko_Nendomatu[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[SHINKYU][KYUFU_KUBUN][SHIKYU_KEITAI];
EXTERN double Kokko_Nendomatu_P[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[SHINKYU][KYUFU_KUBUN][SHIKYU_KEITAI];
EXTERN double Kyoshutukin[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1]
			[MAX_JUKYU - NENREI_SUM + 1][SHIKYU_KEITAI];
EXTERN double Kyoshutukin_Nendomatu[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1]
			[MAX_JUKYU - NENREI_SUM + 1][SHIKYU_KEITAI];
EXTERN double Kyoshutukin_Nendomatu_P[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1]
			[MAX_JUKYU - NENREI_SUM + 1][SHIKYU_KEITAI];
EXTERN double Kyoshutukin_Kokko[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1]
			[MAX_JUKYU - NENREI_SUM + 1][SHIKYU_KEITAI];
EXTERN double Kyoshutukin_Kokko_Nendomatu[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1]
			[MAX_JUKYU - NENREI_SUM + 1][SHIKYU_KEITAI];
EXTERN double Kyoshutukin_Kokko_Nendomatu_P[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1]
			[MAX_JUKYU - NENREI_SUM + 1][SHIKYU_KEITAI];
EXTERN double Tanka[SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1][SHIKYU_KEITAI];
EXTERN double Tanka_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1][SHIKYU_KEITAI];
EXTERN double Tanka_Nendomatu_P[SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1][SHIKYU_KEITAI];
EXTERN double Tanka_Kokko[SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1][SHIKYU_KEITAI];
EXTERN double Tanka_Kokko_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1][SHIKYU_KEITAI];
EXTERN double Tanka_Kokko_Nendomatu_P[SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1][SHIKYU_KEITAI];
EXTERN double Tokubetukokko[SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[TOKUBETU_SHURUI][SHIKYU_KEITAI];
EXTERN double Tokubetukokko_Nendomatu[SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[TOKUBETU_SHURUI][SHIKYU_KEITAI];
EXTERN double Tokubetukokko_Nendomatu_P[SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1]
			[TOKUBETU_SHURUI][SHIKYU_KEITAI];
EXTERN double SanteiTaishou[SEIDO_KUBUN][SAISHUNENDO - SHONENDO + 1][4];
EXTERN double Hiho_Kokunen[SAISHUNENDO - SHONENDO + 1];
EXTERN double Sankyu_Taishou[SAISHUNENDO - SHONENDO + 1];
EXTERN double Ikukyu_Taishou[SAISHUNENDO - SHONENDO + 1];
EXTERN double Kokko_Wariai[SAISHUNENDO - ( SHONENDO - 1 ) + 1];
EXTERN double Tokubetu_Kokko_Wariai[SAISHUNENDO - ( SHONENDO - 1 ) + 1][TOKUBETU_SHURUI];
EXTERN double Cut_ritu[SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - UNDER_63 + 1];
EXTERN double Tumatumi[SEIDO_KUBUN + 1][SAISHUNENDO - TUMATUMI_NENDO + 1];
EXTERN double Tumatumi_2014[SEIDO_KUBUN + 1];
EXTERN double i_rate_tumatumi[SAISHUNENDO - SHONENDO + 1];
