#ifdef OPTION_H_INCLUDED
	#define OPTION_H_INCLUDED
	#define EXTERN
#else
	#define EXTERN	extern
#endif

EXTERN int Option;
EXTERN int OPTION_START;
EXTERN int OP_HIKIAGE_KANKAKU;
EXTERN int KOKKONASHI;

#define OP_MAX_KYOSHUTU_NENREI 65

EXTERN int TOUGOU;
EXTERN double Kasan_Sum[6][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1][3];
EXTERN double Kasanmae_Kyufu[6][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1][SHINKYU][KYUFU_KUBUN][KYUFU_TAISHOU][SHIKYU_KEITAI];
EXTERN double Kasanmae_Kyufu_Nendomatu[6][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1][SHINKYU][KYUFU_KUBUN][KYUFU_TAISHOU][SHIKYU_KEITAI];
EXTERN double Kasanmae_Kyufu_Nendomatu_P[6][SAISHUNENDO - SHONENDO + 1][MAX_JUKYU - NENREI_SUM + 1][SHINKYU][KYUFU_KUBUN][KYUFU_TAISHOU][SHIKYU_KEITAI];
